// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrndawmromycgipospau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybmRhd21yb215Y2dpcG9zcGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzE1MTIsImV4cCI6MjA2NDQ0NzUxMn0.ylTCLY7SkrlJ2U8DuaFAawAgUGDKevc4LhH7SPDQ7PE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);